[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-snowflake-reader"
version = "0.1.0"
description = "MCP server for read-only access to Snowflake databases"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["mcp", "snowflake", "database", "reader"]
authors = [
    { name = "cookie" }
]
dependencies = [
    "snowflake-connector-python",
    "mcp-sdk",
]

[project.scripts]
mcp-snowflake-reader = "main:main"

[tool.hatch.build.targets.wheel]
packages = ["."] 